name: deploy-sudoku
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup golang
        uses: actions/setup-go@v4.1.0
        with:
          go-version: "1.21.0"   
      - name: setup nodejs
        uses: actions/setup-node@v4.0.0
        with:
          node-version-file: .nvmrc
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run gulp build
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
      - run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o site/api ./cmd/serve.go
      - run: rsync -a --delete site/ root@boringsudoku.com:/var/www/sudoku
      - run: ssh root@boringsudoku.com -t "systemctl restart sudoku-api"
